### ISSUE TITLE
mcp2200_hid_read_ee returns incorrect byte

### ISSUE THREAD

**Issue by swolix** [balazsgrill/mcp2200#3]
mcp2200_hid_read_ee returns byte[2] as data, while data is stored in byte[3] (2 is don't care)

following patch fixes this;

diff --git a/src/mcp2200.c b/src/mcp2200.c
index c69c8b0..e52cc28 100644
--- a/src/mcp2200.c
+++ b/src/mcp2200.c
@@ -121,7 +121,7 @@ int mcp2200_hid_read_ee(int connectionID, uint8_t address, uint8_t *data){
        if (rbuffer[0] != MCP2200_HID_COMMAND_READ_EE) return MCP2200_INVALID_RESPONSE;
        if (rbuffer[1] != address) return MCP2200_INVALID_RESPONSE;
 
-       (*data) = (rbuffer[2]);
+       (*data) = (rbuffer[3]);
        return 0;
 }

**Comment by balazsgrill** [comment]
Nice find, thanks.
